version: '3.8'

services:
  postgres-qa:
    image: postgres:16-alpine
    container_name: postgres-qa
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres-qa
      POSTGRES_USER: postgres-qa
      POSTGRES_PASSWORD: 1234
    networks:
      - desenvolvimento-network-qa
  spring-app-qa:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-qa:5432/postgres-qa
    networks:
      - desenvolvimento-network-qa
    depends_on:
      - postgres-qa

networks:
  desenvolvimento-network-qa:
    name: desenvolvimento-network-qa
    driver: bridge